# Site settings
title: "Huynh Xuan Phung's CV"
description: "A resume for Huynh Xuan Phung."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Huynh Xuan Phung"
resume_title:                   "Ph.D in Machine Learning"
resume_contact_email:
  "phunghx@hcmute.edu.vn"
resume_header_contact_info: "Ho Chi Minh City University of Technology and Education | +84967853915 | phunghx@hcmute.edu.vn"
resume_header_intro: "<p>I am Head of Computer Engineering <br/> Information Technology Faculty <br/> Ho Chi Minh City University of Technology and Education, Vietnam </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_publications:    true
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://phunghx.github.io/resume/"
  resume_twitter_url:           "https://twitter.com/phunghx"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/phung-huynh-xuan-88b1173a/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "https://phunghx.github.io/resume/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
